// קובץ שנוצר אוטומטית. לא לערוך ביד: מקור הנתונים הוא data/first-words.json,
// ובונים מחדש עם python3 tools/build_words.py
//
// שישה שלבים, צליל תנועה אחד בכל שלב, לפי סדר הלימוד:
//   1 קמץ ופתח (אָ) · 2 חיריק (אִ) · 3 חולם וקמץ קטן (אוֹ) · 4 שורוק וקובוץ (אוּ)
//   5 צירה וסגול (אֵ) · 6 שווא וחטפים
// השלב של מילה הוא השלב הגבוה ביותר שהניקוד שלה צריך, והוא מחושב בקוד (stage_of
// ב-data/validate_words.py, ו-stageOfText כאן למילים שההורה מוסיף). דגש, נקודות שׁ/שׂ,
// אותיות שקטות (אמות קריאה, ה/א בסוף) ושווא באות האחרונה של מילה (ךְ) לא מעלים שלב.
//
// תחנות: בתוך כל שלב המילים ממוינות לפי מספר האותיות ואז לפי השכיחות (סדר הרשימה),
// ומחולקות ל-round(מספר המילים / 30) תחנות רצופות בגודל כמעט שווה. התחנות ממוספרות
// ברצף מ-1 (תחנות שלב 1 ראשונות). עוברים לתחנה הבאה כש-80% ממילות התחנה נקראו
// נכון לפחות פעם אחת; מילים שנכשלו חוזרות בחזרה.
//
// BASE_WORDS[].level הוא השלב (1-6), station הוא מספר התחנה הגלובלי.

export const LEVELS = [
  { id: 1, name: 'קָמָץ וּפַתַח', sound: 'אָ', stations: [1, 2, 3] },
  { id: 2, name: 'חִירִיק', sound: 'אִ', stations: [4, 5, 6] },
  { id: 3, name: 'חוֹלָם', sound: 'אוֹ', stations: [7, 8] },
  { id: 4, name: 'שׁוּרוּק וְקֻבּוּץ', sound: 'אוּ', stations: [9] },
  { id: 5, name: 'צֵירֵה וְסֶגּוֹל', sound: 'אֵ', stations: [10, 11, 12] },
  { id: 6, name: 'שְׁוָא', sound: 'אְ', stations: [13, 14, 15, 16] },
];

export const STATIONS = [
  { index: 1, stage: 1, n: 1, count: 34 },
  { index: 2, stage: 1, n: 2, count: 33 },
  { index: 3, stage: 1, n: 3, count: 33 },
  { index: 4, stage: 2, n: 1, count: 27 },
  { index: 5, stage: 2, n: 2, count: 27 },
  { index: 6, stage: 2, n: 3, count: 26 },
  { index: 7, stage: 3, n: 1, count: 36 },
  { index: 8, stage: 3, n: 2, count: 36 },
  { index: 9, stage: 4, n: 1, count: 42 },
  { index: 10, stage: 5, n: 1, count: 34 },
  { index: 11, stage: 5, n: 2, count: 33 },
  { index: 12, stage: 5, n: 3, count: 33 },
  { index: 13, stage: 6, n: 1, count: 27 },
  { index: 14, stage: 6, n: 2, count: 27 },
  { index: 15, stage: 6, n: 3, count: 26 },
  { index: 16, stage: 6, n: 4, count: 26 },
];

export const BASE_WORDS = [
  // תחנה 1 · שלב 1, תחנה 1 מתוך 3 · 34 מילים · 2-3 אותיות
  { id: 'af', text: 'אַף', pic: '👃', level: 1, station: 1, letters: 2, category: 'body' },
  { id: 'yad', text: 'יָד', pic: '✋', level: 1, station: 1, letters: 2, category: 'body' },
  { id: 'ma', text: 'מָה', pic: '', level: 1, station: 1, letters: 2, category: 'other' },
  { id: 'saba', text: 'סַבָּא', pic: '👴', level: 1, station: 1, letters: 3, category: 'family' },
  { id: 'cham', text: 'חַם', pic: '', level: 1, station: 1, letters: 2, category: 'adjectives' },
  { id: 'naal', text: 'נַעַל', pic: '👟', level: 1, station: 1, letters: 3, category: 'clothes' },
  { id: 'achat', text: 'אַחַת', pic: '1️⃣', level: 1, station: 1, letters: 3, category: 'numbers' },
  { id: 'katan', text: 'קָטָן', pic: '', level: 1, station: 1, letters: 3, category: 'adjectives' },
  { id: 'achal', text: 'אָכַל', pic: '', level: 1, station: 1, letters: 3, category: 'verbs' },
  { id: 'gan', text: 'גַּן', pic: '🛝', level: 1, station: 1, letters: 2, category: 'places' },
  { id: 'para', text: 'פָּרָה', pic: '🐄', level: 1, station: 1, letters: 3, category: 'animals' },
  { id: 'halav', text: 'חָלָב', pic: '🥛', level: 1, station: 1, letters: 3, category: 'food' },
  { id: 'kar', text: 'קַר', pic: '', level: 1, station: 1, letters: 2, category: 'adjectives' },
  { id: 'pach', text: 'פַּח', pic: '🗑️', level: 1, station: 1, letters: 2, category: 'home' },
  { id: 'yam', text: 'יָם', pic: '🌊', level: 1, station: 1, letters: 2, category: 'nature' },
  { id: 'dag', text: 'דָּג', pic: '🐟', level: 1, station: 1, letters: 2, category: 'animals' },
  { id: 'sham', text: 'שָׁם', pic: '', level: 1, station: 1, letters: 2, category: 'other' },
  { id: 'tzav', text: 'צָב', pic: '🐢', level: 1, station: 1, letters: 2, category: 'animals' },
  { id: 'ba', text: 'בָּא', pic: '', level: 1, station: 1, letters: 2, category: 'verbs' },
  { id: 'kaf', text: 'כַּף', pic: '🥄', level: 1, station: 1, letters: 2, category: 'home' },
  { id: 'bat', text: 'בַּת', pic: '', level: 1, station: 1, letters: 2, category: 'family' },
  { id: 'chag', text: 'חַג', pic: '', level: 1, station: 1, letters: 2, category: 'time' },
  { id: 'gav', text: 'גַּב', pic: '', level: 1, station: 1, letters: 2, category: 'body' },
  { id: 'ratz', text: 'רָץ', pic: '🏃', level: 1, station: 1, letters: 2, category: 'verbs' },
  { id: 'ach', text: 'אָח', pic: '', level: 1, station: 1, letters: 2, category: 'family' },
  { id: 'shar', text: 'שָׁר', pic: '', level: 1, station: 1, letters: 2, category: 'verbs' },
  { id: 'tas', text: 'טָס', pic: '', level: 1, station: 1, letters: 2, category: 'verbs' },
  { id: 'af_verb', text: 'עָף', pic: '', level: 1, station: 1, letters: 2, category: 'verbs' },
  { id: 'kam', text: 'קָם', pic: '', level: 1, station: 1, letters: 2, category: 'verbs' },
  { id: 'daf', text: 'דַּף', pic: '📄', level: 1, station: 1, letters: 2, category: 'toys' },
  { id: 'gag', text: 'גַּג', pic: '', level: 1, station: 1, letters: 2, category: 'home' },
  { id: 'kad', text: 'כַּד', pic: '🏺', level: 1, station: 1, letters: 2, category: 'home' },
  { id: 'sal', text: 'סַל', pic: '🧺', level: 1, station: 1, letters: 2, category: 'home' },
  { id: 'har', text: 'הַר', pic: '⛰️', level: 1, station: 1, letters: 2, category: 'nature' },

  // תחנה 2 · שלב 1, תחנה 2 מתוך 3 · 33 מילים · 3 אותיות
  { id: 'patach', text: 'פָּתַח', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'halach', text: 'הָלַךְ', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'lavan', text: 'לָבָן', pic: '⚪', level: 1, station: 2, letters: 3, category: 'colors' },
  { id: 'shata', text: 'שָׁתָה', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'marak', text: 'מָרָק', pic: '', level: 1, station: 2, letters: 3, category: 'food' },
  { id: 'yashav', text: 'יָשַׁב', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'nafal', text: 'נָפַל', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'aba', text: 'אַבָּא', pic: '👨', level: 1, station: 2, letters: 3, category: 'family' },
  { id: 'nahash', text: 'נָחָשׁ', pic: '🐍', level: 1, station: 2, letters: 3, category: 'animals' },
  { id: 'shafan', text: 'שָׁפָן', pic: '', level: 1, station: 2, letters: 3, category: 'animals' },
  { id: 'chadash', text: 'חָדָשׁ', pic: '', level: 1, station: 2, letters: 3, category: 'adjectives' },
  { id: 'agas', text: 'אַגָּס', pic: '🍐', level: 1, station: 2, letters: 3, category: 'food' },
  { id: 'kafatz', text: 'קָפַץ', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'sagar', text: 'סָגַר', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'sapa', text: 'סַפָּה', pic: '🛋️', level: 1, station: 2, letters: 3, category: 'home' },
  { id: 'lama', text: 'לָמָּה', pic: '', level: 1, station: 2, letters: 3, category: 'other' },
  { id: 'shana', text: 'שָׁנָה', pic: '', level: 1, station: 2, letters: 3, category: 'time' },
  { id: 'bacha', text: 'בָּכָה', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'zarak', text: 'זָרַק', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'raa', text: 'רָאָה', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'anan', text: 'עָנָן', pic: '☁️', level: 1, station: 2, letters: 3, category: 'nature' },
  { id: 'bana', text: 'בָּנָה', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'shaa', text: 'שָׁעָה', pic: '', level: 1, station: 2, letters: 3, category: 'time' },
  { id: 'ahav', text: 'אָהַב', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'chazak', text: 'חָזָק', pic: '', level: 1, station: 2, letters: 3, category: 'adjectives' },
  { id: 'chaya', text: 'חַיָּה', pic: '', level: 1, station: 2, letters: 3, category: 'animals' },
  { id: 'zakan', text: 'זָקָן', pic: '🧔', level: 1, station: 2, letters: 3, category: 'body' },
  { id: 'shabat', text: 'שַׁבָּת', pic: '', level: 1, station: 2, letters: 3, category: 'time' },
  { id: 'zahav', text: 'זָהָב', pic: '', level: 1, station: 2, letters: 3, category: 'colors' },
  { id: 'kara', text: 'קָרָא', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'shama', text: 'שָׁמַע', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },
  { id: 'magaf', text: 'מַגָּף', pic: '🥾', level: 1, station: 2, letters: 3, category: 'clothes' },
  { id: 'rakad', text: 'רָקַד', pic: '', level: 1, station: 2, letters: 3, category: 'verbs' },

  // תחנה 3 · שלב 1, תחנה 3 מתוך 3 · 33 מילים · 3-4 אותיות
  { id: 'banana', text: 'בָּנָנָה', pic: '🍌', level: 1, station: 3, letters: 4, category: 'food' },
  { id: 'matana', text: 'מַתָּנָה', pic: '🎁', level: 1, station: 3, letters: 4, category: 'toys' },
  { id: 'tzalachat', text: 'צַלַּחַת', pic: '🍽️', level: 1, station: 3, letters: 4, category: 'home' },
  { id: 'tabaat', text: 'טַבַּעַת', pic: '💍', level: 1, station: 3, letters: 4, category: 'clothes' },
  { id: 'chava', text: 'חַוָּה', pic: '', level: 1, station: 3, letters: 3, category: 'places' },
  { id: 'barak', text: 'בָּרָק', pic: '⚡', level: 1, station: 3, letters: 3, category: 'nature' },
  { id: 'tayas', text: 'טַיָּס', pic: '🧑‍✈️', level: 1, station: 3, letters: 3, category: 'family' },
  { id: 'salat', text: 'סָלָט', pic: '🥗', level: 1, station: 3, letters: 3, category: 'food' },
  { id: 'nahar', text: 'נָהָר', pic: '', level: 1, station: 3, letters: 3, category: 'nature' },
  { id: 'dayag', text: 'דַּיָּג', pic: '', level: 1, station: 3, letters: 3, category: 'family' },
  { id: 'yaar', text: 'יַעַר', pic: '', level: 1, station: 3, letters: 3, category: 'nature' },
  { id: 'tzayar', text: 'צַיָּר', pic: '🧑‍🎨', level: 1, station: 3, letters: 3, category: 'family' },
  { id: 'batzal', text: 'בָּצָל', pic: '🧅', level: 1, station: 3, letters: 3, category: 'food' },
  { id: 'tabach', text: 'טַבָּח', pic: '🧑‍🍳', level: 1, station: 3, letters: 3, category: 'family' },
  { id: 'panas', text: 'פָּנָס', pic: '🔦', level: 1, station: 3, letters: 3, category: 'home' },
  { id: 'zamar', text: 'זַמָּר', pic: '🧑‍🎤', level: 1, station: 3, letters: 3, category: 'family' },
  { id: 'zanav', text: 'זָנָב', pic: '', level: 1, station: 3, letters: 3, category: 'body' },
  { id: 'machak', text: 'מַחַק', pic: '', level: 1, station: 3, letters: 3, category: 'toys' },
  { id: 'chala', text: 'חַלָּה', pic: '', level: 1, station: 3, letters: 3, category: 'food' },
  { id: 'tzavar', text: 'צַוָּאר', pic: '', level: 1, station: 3, letters: 4, category: 'body' },
  { id: 'gamad', text: 'גַּמָּד', pic: '', level: 1, station: 3, letters: 3, category: 'family' },
  { id: 'tzachak', text: 'צָחַק', pic: '', level: 1, station: 3, letters: 3, category: 'verbs' },
  { id: 'anaf', text: 'עָנָף', pic: '', level: 1, station: 3, letters: 3, category: 'nature' },
  { id: 'zahal', text: 'זַחַל', pic: '🐛', level: 1, station: 3, letters: 3, category: 'animals' },
  { id: 'gamal', text: 'גָּמָל', pic: '🐫', level: 1, station: 3, letters: 3, category: 'animals' },
  { id: 'katav', text: 'כָּתַב', pic: '', level: 1, station: 3, letters: 3, category: 'verbs' },
  { id: 'nachal', text: 'נַחַל', pic: '', level: 1, station: 3, letters: 3, category: 'nature' },
  { id: 'ananas', text: 'אָנָנָס', pic: '🍍', level: 1, station: 3, letters: 4, category: 'food' },
  { id: 'chasa', text: 'חַסָּה', pic: '', level: 1, station: 3, letters: 3, category: 'food' },
  { id: 'machar', text: 'מָחָר', pic: '', level: 1, station: 3, letters: 3, category: 'time' },
  { id: 'ganan', text: 'גַּנָּן', pic: '', level: 1, station: 3, letters: 3, category: 'family' },
  { id: 'hagav', text: 'חָגָב', pic: '', level: 1, station: 3, letters: 3, category: 'animals' },
  { id: 'kabai', text: 'כַּבַּאי', pic: '🧑‍🚒', level: 1, station: 3, letters: 4, category: 'family' },

  // תחנה 4 · שלב 2, תחנה 1 מתוך 3 · 27 מילים · 2-3 אותיות
  { id: 'mayim', text: 'מַיִם', pic: '💧', level: 2, station: 4, letters: 3, category: 'food' },
  { id: 'bayit', text: 'בַּיִת', pic: '🏠', level: 2, station: 4, letters: 3, category: 'home' },
  { id: 'ayin', text: 'עַיִן', pic: '👁️', level: 2, station: 4, letters: 3, category: 'body' },
  { id: 'pil', text: 'פִּיל', pic: '🐘', level: 2, station: 4, letters: 3, category: 'animals' },
  { id: 'tik', text: 'תִּיק', pic: '🎒', level: 2, station: 4, letters: 3, category: 'clothes' },
  { id: 'mita', text: 'מִטָּה', pic: '🛏️', level: 2, station: 4, letters: 3, category: 'home' },
  { id: 'mitz', text: 'מִיץ', pic: '🧃', level: 2, station: 4, letters: 3, category: 'food' },
  { id: 'ish', text: 'אִישׁ', pic: '👨', level: 2, station: 4, letters: 3, category: 'family' },
  { id: 'ima', text: 'אִמָּא', pic: '👩', level: 2, station: 4, letters: 3, category: 'family' },
  { id: 'gina', text: 'גִּנָּה', pic: '', level: 2, station: 4, letters: 3, category: 'places' },
  { id: 'i', text: 'אִי', pic: '🏝️', level: 2, station: 4, letters: 2, category: 'places' },
  { id: 'isha', text: 'אִשָּׁה', pic: '👩', level: 2, station: 4, letters: 3, category: 'family' },
  { id: 'naki', text: 'נָקִי', pic: '', level: 2, station: 4, letters: 3, category: 'adjectives' },
  { id: 'pita', text: 'פִּתָּה', pic: '🫓', level: 2, station: 4, letters: 3, category: 'food' },
  { id: 'mi', text: 'מִי', pic: '', level: 2, station: 4, letters: 2, category: 'other' },
  { id: 'zayit', text: 'זַיִת', pic: '🫒', level: 2, station: 4, letters: 3, category: 'food' },
  { id: 'mila', text: 'מִלָּה', pic: '', level: 2, station: 4, letters: 3, category: 'other' },
  { id: 'nika', text: 'נִקָּה', pic: '', level: 2, station: 4, letters: 3, category: 'verbs' },
  { id: 'kiba', text: 'כִּבָּה', pic: '', level: 2, station: 4, letters: 3, category: 'verbs' },
  { id: 'shir', text: 'שִׁיר', pic: '🎵', level: 2, station: 4, letters: 3, category: 'toys' },
  { id: 'ir', text: 'עִיר', pic: '🏙️', level: 2, station: 4, letters: 3, category: 'places' },
  { id: 'chika', text: 'חִכָּה', pic: '', level: 2, station: 4, letters: 3, category: 'verbs' },
  { id: 'hi', text: 'הִיא', pic: '', level: 2, station: 4, letters: 3, category: 'other' },
  { id: 'tipa', text: 'טִפָּה', pic: '💧', level: 2, station: 4, letters: 3, category: 'nature' },
  { id: 'kita', text: 'כִּתָּה', pic: '', level: 2, station: 4, letters: 3, category: 'places' },
  { id: 'riba', text: 'רִבָּה', pic: '', level: 2, station: 4, letters: 3, category: 'food' },
  { id: 'im', text: 'עִם', pic: '', level: 2, station: 4, letters: 2, category: 'other' },

  // תחנה 5 · שלב 2, תחנה 2 מתוך 3 · 27 מילים · 3-4 אותיות
  { id: 'yadayim', text: 'יָדַיִם', pic: '🙌', level: 2, station: 5, letters: 4, category: 'body' },
  { id: 'shinayim', text: 'שִׁנַּיִם', pic: '', level: 2, station: 5, letters: 4, category: 'body' },
  { id: 'taim', text: 'טָעִים', pic: '', level: 2, station: 5, letters: 4, category: 'adjectives' },
  { id: 'kapit', text: 'כַּפִּית', pic: '', level: 2, station: 5, letters: 4, category: 'home' },
  { id: 'pitza', text: 'פִּיצָה', pic: '🍕', level: 2, station: 5, letters: 4, category: 'food' },
  { id: 'tiras', text: 'תִּירָס', pic: '🌽', level: 2, station: 5, letters: 4, category: 'food' },
  { id: 'shamayim', text: 'שָׁמַיִם', pic: '', level: 2, station: 5, letters: 4, category: 'nature' },
  { id: 'sakin', text: 'סַכִּין', pic: '', level: 2, station: 5, letters: 4, category: 'home' },
  { id: 'karit', text: 'כָּרִית', pic: '', level: 2, station: 5, letters: 4, category: 'home' },
  { id: 'higia', text: 'הִגִּיעַ', pic: '', level: 2, station: 5, letters: 4, category: 'verbs' },
  { id: 'panim', text: 'פָּנִים', pic: '', level: 2, station: 5, letters: 4, category: 'body' },
  { id: 'karich', text: 'כָּרִיךְ', pic: '🥪', level: 2, station: 5, letters: 4, category: 'food' },
  { id: 'naim', text: 'נָעִים', pic: '', level: 2, station: 5, letters: 4, category: 'adjectives' },
  { id: 'mahir', text: 'מָהִיר', pic: '', level: 2, station: 5, letters: 4, category: 'adjectives' },
  { id: 'tzair', text: 'צָעִיר', pic: '', level: 2, station: 5, letters: 4, category: 'adjectives' },
  { id: 'pina', text: 'פִּנָּה', pic: '', level: 2, station: 5, letters: 3, category: 'home' },
  { id: 'ris', text: 'רִיס', pic: '', level: 2, station: 5, letters: 3, category: 'body' },
  { id: 'kayitz', text: 'קַיִץ', pic: '', level: 2, station: 5, letters: 3, category: 'time' },
  { id: 'iti', text: 'אִטִּי', pic: '', level: 2, station: 5, letters: 3, category: 'adjectives' },
  { id: 'kir', text: 'קִיר', pic: '🧱', level: 2, station: 5, letters: 3, category: 'home' },
  { id: 'kis', text: 'כִּיס', pic: '', level: 2, station: 5, letters: 3, category: 'clothes' },
  { id: 'sir', text: 'סִיר', pic: '🍲', level: 2, station: 5, letters: 3, category: 'home' },
  { id: 'sika', text: 'סִכָּה', pic: '', level: 2, station: 5, letters: 3, category: 'clothes' },
  { id: 'piya', text: 'פִּיָּה', pic: '🧚', level: 2, station: 5, letters: 3, category: 'family' },
  { id: 'siach', text: 'שִׂיחַ', pic: '', level: 2, station: 5, letters: 3, category: 'nature' },
  { id: 'kipa', text: 'כִּפָּה', pic: '', level: 2, station: 5, letters: 3, category: 'clothes' },
  { id: 'gir', text: 'גִּיר', pic: '', level: 2, station: 5, letters: 3, category: 'toys' },

  // תחנה 6 · שלב 2, תחנה 3 מתוך 3 · 26 מילים · 4-5 אותיות
  { id: 'masait', text: 'מַשָּׂאִית', pic: '🚚', level: 2, station: 6, letters: 5, category: 'vehicles' },
  { id: 'saviv', text: 'סָבִיב', pic: '', level: 2, station: 6, letters: 4, category: 'other' },
  { id: 'shatiach', text: 'שָׁטִיחַ', pic: '', level: 2, station: 6, letters: 4, category: 'home' },
  { id: 'yamin', text: 'יָמִין', pic: '', level: 2, station: 6, letters: 4, category: 'other' },
  { id: 'bari', text: 'בָּרִיא', pic: '', level: 2, station: 6, letters: 4, category: 'adjectives' },
  { id: 'sira', text: 'סִירָה', pic: '⛵', level: 2, station: 6, letters: 4, category: 'vehicles' },
  { id: 'sakit', text: 'שַׂקִּית', pic: '', level: 2, station: 6, letters: 4, category: 'home' },
  { id: 'nasich', text: 'נָסִיךְ', pic: '🤴', level: 2, station: 6, letters: 4, category: 'family' },
  { id: 'bahir', text: 'בָּהִיר', pic: '', level: 2, station: 6, letters: 4, category: 'adjectives' },
  { id: 'ritza', text: 'רִיצָה', pic: '', level: 2, station: 6, letters: 4, category: 'verbs' },
  { id: 'charif', text: 'חָרִיף', pic: '', level: 2, station: 6, letters: 4, category: 'adjectives' },
  { id: 'tanin', text: 'תַּנִּין', pic: '🐊', level: 2, station: 6, letters: 4, category: 'animals' },
  { id: 'sinar', text: 'סִינָר', pic: '', level: 2, station: 6, letters: 4, category: 'clothes' },
  { id: 'aviv', text: 'אָבִיב', pic: '', level: 2, station: 6, letters: 4, category: 'time' },
  { id: 'gitara', text: 'גִּיטָרָה', pic: '🎸', level: 2, station: 6, letters: 5, category: 'toys' },
  { id: 'tira', text: 'טִירָה', pic: '🏰', level: 2, station: 6, letters: 4, category: 'places' },
  { id: 'tzamid', text: 'צָמִיד', pic: '', level: 2, station: 6, letters: 4, category: 'clothes' },
  { id: 'chida', text: 'חִידָה', pic: '', level: 2, station: 6, letters: 4, category: 'other' },
  { id: 'patish', text: 'פַּטִּישׁ', pic: '🔨', level: 2, station: 6, letters: 4, category: 'home' },
  { id: 'chalil', text: 'חָלִיל', pic: '🪈', level: 2, station: 6, letters: 4, category: 'toys' },
  { id: 'mapit', text: 'מַפִּית', pic: '', level: 2, station: 6, letters: 4, category: 'home' },
  { id: 'kabait', text: 'כַּבָּאִית', pic: '🚒', level: 2, station: 6, letters: 5, category: 'vehicles' },
  { id: 'chatzil', text: 'חָצִיל', pic: '🍆', level: 2, station: 6, letters: 4, category: 'food' },
  { id: 'tzaif', text: 'צָעִיף', pic: '🧣', level: 2, station: 6, letters: 4, category: 'clothes' },
  { id: 'kashit', text: 'קַשִּׁית', pic: '', level: 2, station: 6, letters: 4, category: 'home' },
  { id: 'kalanit', text: 'כַּלָּנִית', pic: '', level: 2, station: 6, letters: 5, category: 'nature' },

  // תחנה 7 · שלב 3, תחנה 1 מתוך 2 · 36 מילים · 2-4 אותיות
  { id: 'lo', text: 'לֹא', pic: '', level: 3, station: 7, letters: 2, category: 'other' },
  { id: 'toda', text: 'תּוֹדָה', pic: '', level: 3, station: 7, letters: 4, category: 'other' },
  { id: 'od', text: 'עוֹד', pic: '', level: 3, station: 7, letters: 3, category: 'other' },
  { id: 'shalom', text: 'שָׁלוֹם', pic: '👋', level: 3, station: 7, letters: 4, category: 'other' },
  { id: 'or', text: 'אוֹר', pic: '💡', level: 3, station: 7, letters: 3, category: 'home' },
  { id: 'rosh', text: 'רֹאשׁ', pic: '', level: 3, station: 7, letters: 3, category: 'body' },
  { id: 'oto', text: 'אוֹטוֹ', pic: '🚗', level: 3, station: 7, letters: 4, category: 'vehicles' },
  { id: 'gadol', text: 'גָּדוֹל', pic: '', level: 3, station: 7, letters: 4, category: 'adjectives' },
  { id: 'tzipor', text: 'צִפּוֹר', pic: '🐦', level: 3, station: 7, letters: 4, category: 'animals' },
  { id: 'kos', text: 'כּוֹס', pic: '', level: 3, station: 7, letters: 3, category: 'home' },
  { id: 'matos', text: 'מָטוֹס', pic: '✈️', level: 3, station: 7, letters: 4, category: 'vehicles' },
  { id: 'tov', text: 'טוֹב', pic: '', level: 3, station: 7, letters: 3, category: 'adjectives' },
  { id: 'dov', text: 'דּוֹב', pic: '🐻', level: 3, station: 7, letters: 3, category: 'animals' },
  { id: 'balon', text: 'בָּלוֹן', pic: '🎈', level: 3, station: 7, letters: 4, category: 'toys' },
  { id: 'kova', text: 'כּוֹבַע', pic: '🧢', level: 3, station: 7, letters: 4, category: 'clothes' },
  { id: 'kof', text: 'קוֹף', pic: '🐒', level: 3, station: 7, letters: 3, category: 'animals' },
  { id: 'shaon', text: 'שָׁעוֹן', pic: '⏰', level: 3, station: 7, letters: 4, category: 'home' },
  { id: 'chalon', text: 'חַלּוֹן', pic: '🪟', level: 3, station: 7, letters: 4, category: 'home' },
  { id: 'sabon', text: 'סַבּוֹן', pic: '🧼', level: 3, station: 7, letters: 4, category: 'home' },
  { id: 'of', text: 'עוֹף', pic: '🍗', level: 3, station: 7, letters: 3, category: 'food' },
  { id: 'hakol', text: 'הַכֹּל', pic: '', level: 3, station: 7, letters: 3, category: 'other' },
  { id: 'bo', text: 'בּוֹא', pic: '', level: 3, station: 7, letters: 3, category: 'verbs' },
  { id: 'yom', text: 'יוֹם', pic: '', level: 3, station: 7, letters: 3, category: 'time' },
  { id: 'chof', text: 'חוֹף', pic: '', level: 3, station: 7, letters: 3, category: 'places' },
  { id: 'kochav', text: 'כּוֹכָב', pic: '⭐', level: 3, station: 7, letters: 4, category: 'nature' },
  { id: 'hol', text: 'חוֹל', pic: '🏖️', level: 3, station: 7, letters: 3, category: 'nature' },
  { id: 'lashon', text: 'לָשׁוֹן', pic: '👅', level: 3, station: 7, letters: 4, category: 'body' },
  { id: 'aron', text: 'אָרוֹן', pic: '', level: 3, station: 7, letters: 4, category: 'home' },
  { id: 'shalosh', text: 'שָׁלוֹשׁ', pic: '3️⃣', level: 3, station: 7, letters: 4, category: 'numbers' },
  { id: 'ratov', text: 'רָטוֹב', pic: '', level: 3, station: 7, letters: 4, category: 'adjectives' },
  { id: 'karov', text: 'קָרוֹב', pic: '', level: 3, station: 7, letters: 4, category: 'adjectives' },
  { id: 'gavoha', text: 'גָּבוֹהַּ', pic: '', level: 3, station: 7, letters: 4, category: 'adjectives' },
  { id: 'kol', text: 'קוֹל', pic: '', level: 3, station: 7, letters: 3, category: 'other' },
  { id: 'shachor', text: 'שָׁחוֹר', pic: '⚫', level: 3, station: 7, letters: 4, category: 'colors' },
  { id: 'dod', text: 'דּוֹד', pic: '', level: 3, station: 7, letters: 3, category: 'family' },
  { id: 'tof', text: 'תּוֹף', pic: '🥁', level: 3, station: 7, letters: 3, category: 'toys' },

  // תחנה 8 · שלב 3, תחנה 2 מתוך 2 · 36 מילים · 4-8 אותיות
  { id: 'tinok', text: 'תִּינוֹק', pic: '👶', level: 3, station: 8, letters: 5, category: 'family' },
  { id: 'shokolad', text: 'שׁוֹקוֹלָד', pic: '🍫', level: 3, station: 8, letters: 6, category: 'food' },
  { id: 'adom', text: 'אָדוֹם', pic: '🔴', level: 3, station: 8, letters: 4, category: 'colors' },
  { id: 'doda', text: 'דּוֹדָה', pic: '', level: 3, station: 8, letters: 4, category: 'family' },
  { id: 'kachol', text: 'כָּחוֹל', pic: '🔵', level: 3, station: 8, letters: 4, category: 'colors' },
  { id: 'monit', text: 'מוֹנִית', pic: '🚕', level: 3, station: 8, letters: 5, category: 'vehicles' },
  { id: 'yarok', text: 'יָרוֹק', pic: '🟢', level: 3, station: 8, letters: 4, category: 'colors' },
  { id: 'matok', text: 'מָתוֹק', pic: '', level: 3, station: 8, letters: 4, category: 'adjectives' },
  { id: 'achot', text: 'אָחוֹת', pic: '', level: 3, station: 8, letters: 4, category: 'family' },
  { id: 'horim', text: 'הוֹרִים', pic: '', level: 3, station: 8, letters: 5, category: 'family' },
  { id: 'mora', text: 'מוֹרָה', pic: '🧑‍🏫', level: 3, station: 8, letters: 4, category: 'family' },
  { id: 'shoko', text: 'שׁוֹקוֹ', pic: '', level: 3, station: 8, letters: 4, category: 'food' },
  { id: 'hayom', text: 'הַיּוֹם', pic: '', level: 3, station: 8, letters: 4, category: 'time' },
  { id: 'robot', text: 'רוֹבּוֹט', pic: '🤖', level: 3, station: 8, letters: 5, category: 'toys' },
  { id: 'yona', text: 'יוֹנָה', pic: '🕊️', level: 3, station: 8, letters: 4, category: 'animals' },
  { id: 'aroch', text: 'אָרוֹךְ', pic: '', level: 3, station: 8, letters: 4, category: 'adjectives' },
  { id: 'tzahov', text: 'צָהוֹב', pic: '🟡', level: 3, station: 8, letters: 4, category: 'colors' },
  { id: 'tolaat', text: 'תּוֹלַעַת', pic: '🪱', level: 3, station: 8, letters: 5, category: 'animals' },
  { id: 'varod', text: 'וָרוֹד', pic: '🩷', level: 3, station: 8, letters: 4, category: 'colors' },
  { id: 'limon', text: 'לִימוֹן', pic: '🍋', level: 3, station: 8, letters: 5, category: 'food' },
  { id: 'afor', text: 'אָפוֹר', pic: '🩶', level: 3, station: 8, letters: 4, category: 'colors' },
  { id: 'sagol', text: 'סָגוֹל', pic: '🟣', level: 3, station: 8, letters: 4, category: 'colors' },
  { id: 'garon', text: 'גָּרוֹן', pic: '', level: 3, station: 8, letters: 4, category: 'body' },
  { id: 'rimon', text: 'רִמּוֹן', pic: '', level: 3, station: 8, letters: 4, category: 'food' },
  { id: 'katom', text: 'כָּתוֹם', pic: '🟠', level: 3, station: 8, letters: 4, category: 'colors' },
  { id: 'kokos', text: 'קוֹקוֹס', pic: '🥥', level: 3, station: 8, letters: 5, category: 'food' },
  { id: 'kipod', text: 'קִפּוֹד', pic: '🦔', level: 3, station: 8, letters: 4, category: 'animals' },
  { id: 'kinor', text: 'כִּנּוֹר', pic: '🎻', level: 3, station: 8, letters: 4, category: 'toys' },
  { id: 'rachok', text: 'רָחוֹק', pic: '', level: 3, station: 8, letters: 4, category: 'adjectives' },
  { id: 'manof', text: 'מָנוֹף', pic: '🏗️', level: 3, station: 8, letters: 4, category: 'vehicles' },
  { id: 'iparon', text: 'עִפָּרוֹן', pic: '✏️', level: 3, station: 8, letters: 5, category: 'toys' },
  { id: 'chilazon', text: 'חִלָּזוֹן', pic: '🐌', level: 3, station: 8, letters: 5, category: 'animals' },
  { id: 'masok', text: 'מַסּוֹק', pic: '🚁', level: 3, station: 8, letters: 4, category: 'vehicles' },
  { id: 'ofanayim', text: 'אוֹפַנַּיִם', pic: '🚲', level: 3, station: 8, letters: 6, category: 'vehicles' },
  { id: 'ofanoa', text: 'אוֹפַנּוֹעַ', pic: '🏍️', level: 3, station: 8, letters: 6, category: 'vehicles' },
  { id: 'hipopotam', text: 'הִיפּוֹפּוֹטָם', pic: '🦛', level: 3, station: 8, letters: 8, category: 'animals' },

  // תחנה 9 · שלב 4, תחנה 1 מתוך 1 · 42 מילים · 3-7 אותיות
  { id: 'kadur', text: 'כַּדּוּר', pic: '⚽', level: 4, station: 9, letters: 4, category: 'toys' },
  { id: 'uga', text: 'עוּגָה', pic: '🍰', level: 4, station: 9, letters: 4, category: 'food' },
  { id: 'buba', text: 'בֻּבָּה', pic: '', level: 4, station: 9, letters: 3, category: 'toys' },
  { id: 'sipur', text: 'סִפּוּר', pic: '', level: 4, station: 9, letters: 4, category: 'toys' },
  { id: 'chatul', text: 'חָתוּל', pic: '🐈', level: 4, station: 9, letters: 4, category: 'animals' },
  { id: 'sus', text: 'סוּס', pic: '🐴', level: 4, station: 9, letters: 3, category: 'animals' },
  { id: 'ugiya', text: 'עוּגִיָּה', pic: '🍪', level: 4, station: 9, letters: 5, category: 'food' },
  { id: 'dubi', text: 'דֻּבִּי', pic: '🧸', level: 4, station: 9, letters: 3, category: 'toys' },
  { id: 'tapuah', text: 'תַּפּוּחַ', pic: '🍎', level: 4, station: 9, letters: 4, category: 'food' },
  { id: 'otobus', text: 'אוֹטוֹבּוּס', pic: '🚌', level: 4, station: 9, letters: 7, category: 'vehicles' },
  { id: 'tut', text: 'תּוּת', pic: '🍓', level: 4, station: 9, letters: 3, category: 'food' },
  { id: 'ruach', text: 'רוּחַ', pic: '💨', level: 4, station: 9, letters: 3, category: 'nature' },
  { id: 'kum', text: 'קוּם', pic: '', level: 4, station: 9, letters: 3, category: 'verbs' },
  { id: 'shum', text: 'שׁוּם', pic: '🧄', level: 4, station: 9, letters: 3, category: 'food' },
  { id: 'tapuz', text: 'תַּפּוּז', pic: '🍊', level: 4, station: 9, letters: 4, category: 'food' },
  { id: 'rutz', text: 'רוּץ', pic: '', level: 4, station: 9, letters: 3, category: 'verbs' },
  { id: 'chashuch', text: 'חָשׁוּךְ', pic: '', level: 4, station: 9, letters: 4, category: 'adjectives' },
  { id: 'chamud', text: 'חָמוּד', pic: '', level: 4, station: 9, letters: 4, category: 'adjectives' },
  { id: 'tuki', text: 'תֻּכִּי', pic: '🦜', level: 4, station: 9, letters: 3, category: 'animals' },
  { id: 'kubiya', text: 'קֻבִּיָּה', pic: '', level: 4, station: 9, letters: 4, category: 'toys' },
  { id: 'shavur', text: 'שָׁבוּר', pic: '', level: 4, station: 9, letters: 4, category: 'adjectives' },
  { id: 'chipushit', text: 'חִפּוּשִׁית', pic: '🪲', level: 4, station: 9, letters: 6, category: 'animals' },
  { id: 'shavua', text: 'שָׁבוּעַ', pic: '', level: 4, station: 9, letters: 4, category: 'time' },
  { id: 'tush', text: 'טוּשׁ', pic: '', level: 4, station: 9, letters: 3, category: 'toys' },
  { id: 'tanur', text: 'תַּנּוּר', pic: '', level: 4, station: 9, letters: 4, category: 'home' },
  { id: 'hu', text: 'הוּא', pic: '', level: 4, station: 9, letters: 3, category: 'other' },
  { id: 'buot', text: 'בּוּעוֹת', pic: '🫧', level: 4, station: 9, letters: 5, category: 'toys' },
  { id: 'nura', text: 'נוּרָה', pic: '💡', level: 4, station: 9, letters: 4, category: 'home' },
  { id: 'chum', text: 'חוּם', pic: '🟤', level: 4, station: 9, letters: 3, category: 'colors' },
  { id: 'guf', text: 'גּוּף', pic: '', level: 4, station: 9, letters: 3, category: 'body' },
  { id: 'atzuv', text: 'עָצוּב', pic: '', level: 4, station: 9, letters: 4, category: 'adjectives' },
  { id: 'tzura', text: 'צוּרָה', pic: '', level: 4, station: 9, letters: 4, category: 'other' },
  { id: 'sulam', text: 'סֻלָּם', pic: '🪜', level: 4, station: 9, letters: 3, category: 'home' },
  { id: 'chiyuch', text: 'חִיּוּךְ', pic: '😊', level: 4, station: 9, letters: 4, category: 'other' },
  { id: 'chibuk', text: 'חִבּוּק', pic: '🤗', level: 4, station: 9, letters: 4, category: 'other' },
  { id: 'tziyur', text: 'צִיּוּר', pic: '', level: 4, station: 9, letters: 4, category: 'toys' },
  { id: 'sufa', text: 'סוּפָה', pic: '', level: 4, station: 9, letters: 4, category: 'nature' },
  { id: 'shual', text: 'שׁוּעָל', pic: '🦊', level: 4, station: 9, letters: 4, category: 'animals' },
  { id: 'chamutz', text: 'חָמוּץ', pic: '', level: 4, station: 9, letters: 4, category: 'adjectives' },
  { id: 'igul', text: 'עִגּוּל', pic: '', level: 4, station: 9, letters: 4, category: 'other' },
  { id: 'chumus', text: 'חוּמוּס', pic: '', level: 4, station: 9, letters: 5, category: 'food' },
  { id: 'sukariya', text: 'סֻכָּרִיָּה', pic: '🍭', level: 4, station: 9, letters: 5, category: 'food' },

  // תחנה 10 · שלב 5, תחנה 1 מתוך 3 · 34 מילים · 2-3 אותיות
  { id: 'ken', text: 'כֵּן', pic: '', level: 5, station: 10, letters: 2, category: 'other' },
  { id: 'ze', text: 'זֶה', pic: '', level: 5, station: 10, letters: 2, category: 'other' },
  { id: 'pe', text: 'פֶּה', pic: '👄', level: 5, station: 10, letters: 2, category: 'body' },
  { id: 'ein', text: 'אֵין', pic: '', level: 5, station: 10, letters: 3, category: 'other' },
  { id: 'kelev', text: 'כֶּלֶב', pic: '🐕', level: 5, station: 10, letters: 3, category: 'animals' },
  { id: 'echad', text: 'אֶחָד', pic: '1️⃣', level: 5, station: 10, letters: 3, category: 'numbers' },
  { id: 'sefer', text: 'סֵפֶר', pic: '📖', level: 5, station: 10, letters: 3, category: 'toys' },
  { id: 'ten', text: 'תֵּן', pic: '', level: 5, station: 10, letters: 2, category: 'verbs' },
  { id: 'yeled', text: 'יֶלֶד', pic: '🧒', level: 5, station: 10, letters: 3, category: 'family' },
  { id: 'regel', text: 'רֶגֶל', pic: '🦵', level: 5, station: 10, letters: 3, category: 'body' },
  { id: 'etz', text: 'עֵץ', pic: '🌳', level: 5, station: 10, letters: 2, category: 'nature' },
  { id: 'kise', text: 'כִּסֵּא', pic: '🪑', level: 5, station: 10, letters: 3, category: 'home' },
  { id: 'yesh', text: 'יֵשׁ', pic: '', level: 5, station: 10, letters: 2, category: 'other' },
  { id: 'delet', text: 'דֶּלֶת', pic: '🚪', level: 5, station: 10, letters: 3, category: 'home' },
  { id: 'beten', text: 'בֶּטֶן', pic: '', level: 5, station: 10, letters: 3, category: 'body' },
  { id: 'yashen', text: 'יָשֵׁן', pic: '', level: 5, station: 10, letters: 3, category: 'verbs' },
  { id: 'lehem', text: 'לֶחֶם', pic: '🍞', level: 5, station: 10, letters: 3, category: 'food' },
  { id: 'gezer', text: 'גֶּזֶר', pic: '🥕', level: 5, station: 10, letters: 3, category: 'food' },
  { id: 'geshem', text: 'גֶּשֶׁם', pic: '🌧️', level: 5, station: 10, letters: 3, category: 'nature' },
  { id: 'gerev', text: 'גֶּרֶב', pic: '🧦', level: 5, station: 10, letters: 3, category: 'clothes' },
  { id: 'perach', text: 'פֶּרַח', pic: '🌸', level: 5, station: 10, letters: 3, category: 'nature' },
  { id: 'shemesh', text: 'שֶׁמֶשׁ', pic: '☀️', level: 5, station: 10, letters: 3, category: 'nature' },
  { id: 'cheder', text: 'חֶדֶר', pic: '', level: 5, station: 10, letters: 3, category: 'home' },
  { id: 'shen', text: 'שֵׁן', pic: '🦷', level: 5, station: 10, letters: 2, category: 'body' },
  { id: 'kafe', text: 'קָפֶה', pic: '☕', level: 5, station: 10, letters: 3, category: 'food' },
  { id: 'yafe', text: 'יָפֶה', pic: '', level: 5, station: 10, letters: 3, category: 'adjectives' },
  { id: 'sear', text: 'שֵׂעָר', pic: '', level: 5, station: 10, letters: 3, category: 'body' },
  { id: 'lev', text: 'לֵב', pic: '❤️', level: 5, station: 10, letters: 2, category: 'body' },
  { id: 'te', text: 'תֵּה', pic: '🍵', level: 5, station: 10, letters: 2, category: 'food' },
  { id: 'esh', text: 'אֵשׁ', pic: '🔥', level: 5, station: 10, letters: 2, category: 'nature' },
  { id: 'shesh', text: 'שֵׁשׁ', pic: '6️⃣', level: 5, station: 10, letters: 2, category: 'numbers' },
  { id: 'kan', text: 'קֵן', pic: '🪺', level: 5, station: 10, letters: 2, category: 'nature' },
  { id: 'ner', text: 'נֵר', pic: '🕯️', level: 5, station: 10, letters: 2, category: 'home' },
  { id: 'et', text: 'עֵט', pic: '🖊️', level: 5, station: 10, letters: 2, category: 'toys' },

  // תחנה 11 · שלב 5, תחנה 2 מתוך 3 · 33 מילים · 3 אותיות
  { id: 'yareach', text: 'יָרֵחַ', pic: '🌙', level: 5, station: 11, letters: 3, category: 'nature' },
  { id: 'chaver', text: 'חָבֵר', pic: '', level: 5, station: 11, letters: 3, category: 'family' },
  { id: 'enav', text: 'עֵנָב', pic: '🍇', level: 5, station: 11, letters: 3, category: 'food' },
  { id: 'sichek', text: 'שִׂחֵק', pic: '', level: 5, station: 11, letters: 3, category: 'verbs' },
  { id: 'even', text: 'אֶבֶן', pic: '🪨', level: 5, station: 11, letters: 3, category: 'nature' },
  { id: 'sameach', text: 'שָׂמֵחַ', pic: '', level: 5, station: 11, letters: 3, category: 'adjectives' },
  { id: 'erev', text: 'עֶרֶב', pic: '', level: 5, station: 11, letters: 3, category: 'time' },
  { id: 'namer', text: 'נָמֵר', pic: '🐅', level: 5, station: 11, letters: 3, category: 'animals' },
  { id: 'chamesh', text: 'חָמֵשׁ', pic: '5️⃣', level: 5, station: 11, letters: 3, category: 'numbers' },
  { id: 'eser', text: 'עֶשֶׂר', pic: '🔟', level: 5, station: 11, letters: 3, category: 'numbers' },
  { id: 'shaket', text: 'שָׁקֵט', pic: '', level: 5, station: 11, letters: 3, category: 'adjectives' },
  { id: 'chevel', text: 'חֶבֶל', pic: '🪢', level: 5, station: 11, letters: 3, category: 'home' },
  { id: 'ayef', text: 'עָיֵף', pic: '', level: 5, station: 11, letters: 3, category: 'adjectives' },
  { id: 'sheva', text: 'שֶׁבַע', pic: '7️⃣', level: 5, station: 11, letters: 3, category: 'numbers' },
  { id: 'ale', text: 'עָלֶה', pic: '🍃', level: 5, station: 11, letters: 3, category: 'nature' },
  { id: 'melach', text: 'מֶלַח', pic: '🧂', level: 5, station: 11, letters: 3, category: 'food' },
  { id: 'kashe', text: 'קָשֶׁה', pic: '', level: 5, station: 11, letters: 3, category: 'adjectives' },
  { id: 'kaved', text: 'כָּבֵד', pic: '', level: 5, station: 11, letters: 3, category: 'adjectives' },
  { id: 'mea', text: 'מֵאָה', pic: '💯', level: 5, station: 11, letters: 3, category: 'numbers' },
  { id: 'melech', text: 'מֶלֶךְ', pic: '', level: 5, station: 11, letters: 3, category: 'family' },
  { id: 'deshe', text: 'דֶּשֶׁא', pic: '', level: 5, station: 11, letters: 3, category: 'nature' },
  { id: 'degel', text: 'דֶּגֶל', pic: '', level: 5, station: 11, letters: 3, category: 'toys' },
  { id: 'tzeva', text: 'צֶבַע', pic: '🎨', level: 5, station: 11, letters: 3, category: 'toys' },
  { id: 'tesha', text: 'תֵּשַׁע', pic: '9️⃣', level: 5, station: 11, letters: 3, category: 'numbers' },
  { id: 'efes', text: 'אֶפֶס', pic: '0️⃣', level: 5, station: 11, letters: 3, category: 'numbers' },
  { id: 'kerach', text: 'קֶרַח', pic: '🧊', level: 5, station: 11, letters: 3, category: 'nature' },
  { id: 'sade', text: 'שָׂדֶה', pic: '', level: 5, station: 11, letters: 3, category: 'nature' },
  { id: 'etzem', text: 'עֶצֶם', pic: '🦴', level: 5, station: 11, letters: 3, category: 'body' },
  { id: 'sheleg', text: 'שֶׁלֶג', pic: '❄️', level: 5, station: 11, letters: 3, category: 'nature' },
  { id: 'katef', text: 'כָּתֵף', pic: '', level: 5, station: 11, letters: 3, category: 'body' },
  { id: 'raev', text: 'רָעֵב', pic: '', level: 5, station: 11, letters: 3, category: 'adjectives' },
  { id: 'beged', text: 'בֶּגֶד', pic: '', level: 5, station: 11, letters: 3, category: 'clothes' },
  { id: 'keshet', text: 'קֶשֶׁת', pic: '🌈', level: 5, station: 11, letters: 3, category: 'nature' },

  // תחנה 12 · שלב 5, תחנה 3 מתוך 3 · 33 מילים · 3-5 אותיות
  { id: 'rotze', text: 'רוֹצֶה', pic: '', level: 5, station: 12, letters: 4, category: 'verbs' },
  { id: 'ochel', text: 'אוֹכֶל', pic: '', level: 5, station: 12, letters: 4, category: 'food' },
  { id: 'eifo', text: 'אֵיפֹה', pic: '', level: 5, station: 12, letters: 4, category: 'other' },
  { id: 'einayim', text: 'עֵינַיִם', pic: '👀', level: 5, station: 12, letters: 5, category: 'body' },
  { id: 'holech', text: 'הוֹלֵךְ', pic: '', level: 5, station: 12, letters: 4, category: 'verbs' },
  { id: 'telefon', text: 'טֶלֶפוֹן', pic: '☎️', level: 5, station: 12, letters: 5, category: 'home' },
  { id: 'beitza', text: 'בֵּיצָה', pic: '🥚', level: 5, station: 12, letters: 4, category: 'food' },
  { id: 'rakevet', text: 'רַכֶּבֶת', pic: '🚂', level: 5, station: 12, letters: 4, category: 'vehicles' },
  { id: 'shote', text: 'שׁוֹתֶה', pic: '', level: 5, station: 12, letters: 4, category: 'verbs' },
  { id: 'yoshev', text: 'יוֹשֵׁב', pic: '', level: 5, station: 12, letters: 4, category: 'verbs' },
  { id: 'ozen', text: 'אוֹזֶן', pic: '👂', level: 5, station: 12, letters: 4, category: 'body' },
  { id: 'orez', text: 'אוֹרֶז', pic: '🍚', level: 5, station: 12, letters: 4, category: 'food' },
  { id: 'boche', text: 'בּוֹכֶה', pic: '', level: 5, station: 12, letters: 4, category: 'verbs' },
  { id: 'ohev', text: 'אוֹהֵב', pic: '', level: 5, station: 12, letters: 4, category: 'verbs' },
  { id: 'kofetz', text: 'קוֹפֵץ', pic: '', level: 5, station: 12, letters: 4, category: 'verbs' },
  { id: 'boker', text: 'בּוֹקֶר', pic: '', level: 5, station: 12, letters: 4, category: 'time' },
  { id: 'rofe', text: 'רוֹפֵא', pic: '🧑‍⚕️', level: 5, station: 12, letters: 4, category: 'family' },
  { id: 'magevet', text: 'מַגֶּבֶת', pic: '', level: 5, station: 12, letters: 4, category: 'home' },
  { id: 'tzochek', text: 'צוֹחֵק', pic: '', level: 5, station: 12, letters: 4, category: 'verbs' },
  { id: 'chole', text: 'חוֹלֶה', pic: '', level: 5, station: 12, letters: 4, category: 'adjectives' },
  { id: 'roked', text: 'רוֹקֵד', pic: '', level: 5, station: 12, letters: 4, category: 'verbs' },
  { id: 'pazel', text: 'פָּאזֶל', pic: '🧩', level: 5, station: 12, letters: 4, category: 'toys' },
  { id: 'super', text: 'סוּפֶּר', pic: '', level: 5, station: 12, letters: 4, category: 'places' },
  { id: 'leitzan', text: 'לֵיצָן', pic: '🤡', level: 5, station: 12, letters: 4, category: 'family' },
  { id: 'chodesh', text: 'חוֹדֶשׁ', pic: '', level: 5, station: 12, letters: 4, category: 'time' },
  { id: 'melon', text: 'מֵלוֹן', pic: '🍈', level: 5, station: 12, letters: 4, category: 'food' },
  { id: 'choref', text: 'חוֹרֶף', pic: '', level: 5, station: 12, letters: 4, category: 'time' },
  { id: 'male', text: 'מָלֵא', pic: '', level: 5, station: 12, letters: 3, category: 'adjectives' },
  { id: 'vered', text: 'וֶרֶד', pic: '🌹', level: 5, station: 12, letters: 3, category: 'nature' },
  { id: 'keter', text: 'כֶּתֶר', pic: '👑', level: 5, station: 12, letters: 3, category: 'clothes' },
  { id: 'yavesh', text: 'יָבֵשׁ', pic: '', level: 5, station: 12, letters: 3, category: 'adjectives' },
  { id: 'ganenet', text: 'גַּנֶּנֶת', pic: '', level: 5, station: 12, letters: 4, category: 'family' },
  { id: 'raketa', text: 'רָקֶטָה', pic: '🚀', level: 5, station: 12, letters: 4, category: 'vehicles' },

  // תחנה 13 · שלב 6, תחנה 1 מתוך 4 · 27 מילים · 3-4 אותיות
  { id: 'ani', text: 'אֲנִי', pic: '', level: 6, station: 13, letters: 3, category: 'other' },
  { id: 'savta', text: 'סַבְתָּא', pic: '👵', level: 6, station: 13, letters: 4, category: 'family' },
  { id: 'parpar', text: 'פַּרְפַּר', pic: '🦋', level: 6, station: 13, letters: 4, category: 'animals' },
  { id: 'chultza', text: 'חֻלְצָה', pic: '👕', level: 6, station: 13, letters: 4, category: 'clothes' },
  { id: 'arye', text: 'אַרְיֵה', pic: '🦁', level: 6, station: 13, letters: 4, category: 'animals' },
  { id: 'yalda', text: 'יַלְדָּה', pic: '👧', level: 6, station: 13, letters: 4, category: 'family' },
  { id: 'shulchan', text: 'שֻׁלְחָן', pic: '', level: 6, station: 13, letters: 4, category: 'home' },
  { id: 'mischak', text: 'מִשְׂחָק', pic: '', level: 6, station: 13, letters: 4, category: 'toys' },
  { id: 'barvaz', text: 'בַּרְוָז', pic: '🦆', level: 6, station: 13, letters: 4, category: 'animals' },
  { id: 'arnav', text: 'אַרְנָב', pic: '🐇', level: 6, station: 13, letters: 4, category: 'animals' },
  { id: 'etzba', text: 'אֶצְבַּע', pic: '', level: 6, station: 13, letters: 4, category: 'body' },
  { id: 'layla', text: 'לַיְלָה', pic: '', level: 6, station: 13, letters: 4, category: 'time' },
  { id: 'meil', text: 'מְעִיל', pic: '🧥', level: 6, station: 13, letters: 4, category: 'clothes' },
  { id: 'migdal', text: 'מִגְדָּל', pic: '', level: 6, station: 13, letters: 4, category: 'toys' },
  { id: 'pasta', text: 'פַּסְטָה', pic: '🍝', level: 6, station: 13, letters: 4, category: 'food' },
  { id: 'agala', text: 'עֲגָלָה', pic: '', level: 6, station: 13, letters: 4, category: 'vehicles' },
  { id: 'achbar', text: 'עַכְבָּר', pic: '🐭', level: 6, station: 13, letters: 4, category: 'animals' },
  { id: 'kvish', text: 'כְּבִישׁ', pic: '', level: 6, station: 13, letters: 4, category: 'places' },
  { id: 'brecha', text: 'בְּרֵכָה', pic: '', level: 6, station: 13, letters: 4, category: 'places' },
  { id: 'chamor', text: 'חֲמוֹר', pic: '🫏', level: 6, station: 13, letters: 4, category: 'animals' },
  { id: 'kivsa', text: 'כִּבְשָׂה', pic: '🐑', level: 6, station: 13, letters: 4, category: 'animals' },
  { id: 'mafteach', text: 'מַפְתֵּחַ', pic: '🔑', level: 6, station: 13, letters: 4, category: 'home' },
  { id: 'niyar', text: 'נְיָר', pic: '', level: 6, station: 13, letters: 3, category: 'home' },
  { id: 'pri', text: 'פְּרִי', pic: '', level: 6, station: 13, letters: 3, category: 'nature' },
  { id: 'dvash', text: 'דְּבַשׁ', pic: '🍯', level: 6, station: 13, letters: 3, category: 'food' },
  { id: 'kfar', text: 'כְּפָר', pic: '', level: 6, station: 13, letters: 3, category: 'places' },
  { id: 'zeev', text: 'זְאֵב', pic: '🐺', level: 6, station: 13, letters: 3, category: 'animals' },

  // תחנה 14 · שלב 6, תחנה 2 מתוך 4 · 27 מילים · 4 אותיות
  { id: 'mazleg', text: 'מַזְלֵג', pic: '', level: 6, station: 14, letters: 4, category: 'home' },
  { id: 'kufsa', text: 'קֻפְסָה', pic: '📦', level: 6, station: 14, letters: 4, category: 'home' },
  { id: 'chavera', text: 'חֲבֵרָה', pic: '', level: 6, station: 14, letters: 4, category: 'family' },
  { id: 'ahava', text: 'אַהֲבָה', pic: '', level: 6, station: 14, letters: 4, category: 'other' },
  { id: 'mitbach', text: 'מִטְבָּח', pic: '', level: 6, station: 14, letters: 4, category: 'home' },
  { id: 'shtayim', text: 'שְׁתַּיִם', pic: '2️⃣', level: 6, station: 14, letters: 4, category: 'numbers' },
  { id: 'mekarer', text: 'מְקָרֵר', pic: '', level: 6, station: 14, letters: 4, category: 'home' },
  { id: 'simcha', text: 'שִׂמְחָה', pic: '', level: 6, station: 14, letters: 4, category: 'other' },
  { id: 'arba', text: 'אַרְבַּע', pic: '4️⃣', level: 6, station: 14, letters: 4, category: 'numbers' },
  { id: 'oniya', text: 'אֳנִיָּה', pic: '🚢', level: 6, station: 14, letters: 4, category: 'vehicles' },
  { id: 'zebra', text: 'זֶבְּרָה', pic: '🦓', level: 6, station: 14, letters: 4, category: 'animals' },
  { id: 'mara', text: 'מַרְאָה', pic: '🪞', level: 6, station: 14, letters: 4, category: 'home' },
  { id: 'nemala', text: 'נְמָלָה', pic: '🐜', level: 6, station: 14, letters: 4, category: 'animals' },
  { id: 'zvuv', text: 'זְבוּב', pic: '🪰', level: 6, station: 14, letters: 4, category: 'animals' },
  { id: 'michtav', text: 'מִכְתָּב', pic: '✉️', level: 6, station: 14, letters: 4, category: 'home' },
  { id: 'machshev', text: 'מַחְשֵׁב', pic: '💻', level: 6, station: 14, letters: 4, category: 'home' },
  { id: 'simla', text: 'שִׂמְלָה', pic: '👗', level: 6, station: 14, letters: 4, category: 'clothes' },
  { id: 'chanut', text: 'חֲנוּת', pic: '🏪', level: 6, station: 14, letters: 4, category: 'places' },
  { id: 'mesiba', text: 'מְסִבָּה', pic: '🎉', level: 6, station: 14, letters: 4, category: 'other' },
  { id: 'migrash', text: 'מִגְרָשׁ', pic: '', level: 6, station: 14, letters: 4, category: 'places' },
  { id: 'malka', text: 'מַלְכָּה', pic: '', level: 6, station: 14, letters: 4, category: 'family' },
  { id: 'galgal', text: 'גַּלְגַּל', pic: '🛞', level: 6, station: 14, letters: 4, category: 'vehicles' },
  { id: 'tachana', text: 'תַּחֲנָה', pic: '🚉', level: 6, station: 14, letters: 4, category: 'places' },
  { id: 'shvil', text: 'שְׁבִיל', pic: '', level: 6, station: 14, letters: 4, category: 'places' },
  { id: 'achshav', text: 'עַכְשָׁו', pic: '', level: 6, station: 14, letters: 4, category: 'time' },
  { id: 'nechmad', text: 'נֶחְמָד', pic: '', level: 6, station: 14, letters: 4, category: 'adjectives' },
  { id: 'rechov', text: 'רְחוֹב', pic: '', level: 6, station: 14, letters: 4, category: 'places' },

  // תחנה 15 · שלב 6, תחנה 3 מתוך 4 · 26 מילים · 5 אותיות
  { id: 'bakbuk', text: 'בַּקְבּוּק', pic: '', level: 6, station: 15, letters: 5, category: 'home' },
  { id: 'naalayim', text: 'נַעֲלַיִם', pic: '', level: 6, station: 15, letters: 5, category: 'clothes' },
  { id: 'bevakasha', text: 'בְּבַקָּשָׁה', pic: '', level: 6, station: 15, letters: 5, category: 'other' },
  { id: 'glida', text: 'גְּלִידָה', pic: '🍦', level: 6, station: 15, letters: 5, category: 'food' },
  { id: 'gvina', text: 'גְּבִינָה', pic: '🧀', level: 6, station: 15, letters: 5, category: 'food' },
  { id: 'garbayim', text: 'גַּרְבַּיִם', pic: '🧦', level: 6, station: 15, letters: 5, category: 'clothes' },
  { id: 'nadneda', text: 'נַדְנֵדָה', pic: '', level: 6, station: 15, letters: 5, category: 'toys' },
  { id: 'meluchlach', text: 'מְלֻכְלָךְ', pic: '', level: 6, station: 15, letters: 5, category: 'adjectives' },
  { id: 'smicha', text: 'שְׂמִיכָה', pic: '', level: 6, station: 15, letters: 5, category: 'home' },
  { id: 'chavita', text: 'חֲבִיתָה', pic: '', level: 6, station: 15, letters: 5, category: 'food' },
  { id: 'slicha', text: 'סְלִיחָה', pic: '', level: 6, station: 15, letters: 5, category: 'other' },
  { id: 'tzfardea', text: 'צְפַרְדֵּעַ', pic: '🐸', level: 6, station: 15, letters: 5, category: 'animals' },
  { id: 'tmuna', text: 'תְּמוּנָה', pic: '🖼️', level: 6, station: 15, letters: 5, category: 'home' },
  { id: 'avatiach', text: 'אֲבַטִּיחַ', pic: '🍉', level: 6, station: 15, letters: 5, category: 'food' },
  { id: 'miklachat', text: 'מִקְלַחַת', pic: '🚿', level: 6, station: 15, letters: 5, category: 'home' },
  { id: 'matzchik', text: 'מַצְחִיק', pic: '', level: 6, station: 15, letters: 5, category: 'adjectives' },
  { id: 'shnitzel', text: 'שְׁנִיצֶל', pic: '', level: 6, station: 15, letters: 5, category: 'food' },
  { id: 'mishpacha', text: 'מִשְׁפָּחָה', pic: '👪', level: 6, station: 15, letters: 5, category: 'family' },
  { id: 'shmone', text: 'שְׁמוֹנֶה', pic: '8️⃣', level: 6, station: 15, letters: 5, category: 'numbers' },
  { id: 'dvora', text: 'דְּבוֹרָה', pic: '🐝', level: 6, station: 15, letters: 5, category: 'animals' },
  { id: 'hafta', text: 'הַפְתָּעָה', pic: '', level: 6, station: 15, letters: 5, category: 'other' },
  { id: 'tzaatzua', text: 'צַעֲצוּעַ', pic: '', level: 6, station: 15, letters: 5, category: 'toys' },
  { id: 'anachnu', text: 'אֲנַחְנוּ', pic: '', level: 6, station: 15, letters: 5, category: 'other' },
  { id: 'efroach', text: 'אֶפְרוֹחַ', pic: '🐤', level: 6, station: 15, letters: 5, category: 'animals' },
  { id: 'nesicha', text: 'נְסִיכָה', pic: '👸', level: 6, station: 15, letters: 5, category: 'family' },
  { id: 'misada', text: 'מִסְעָדָה', pic: '', level: 6, station: 15, letters: 5, category: 'places' },

  // תחנה 16 · שלב 6, תחנה 4 מתוך 4 · 26 מילים · 5-7 אותיות
  { id: 'mechonit', text: 'מְכוֹנִית', pic: '🚗', level: 6, station: 16, letters: 6, category: 'vehicles' },
  { id: 'michnasayim', text: 'מִכְנָסַיִם', pic: '👖', level: 6, station: 16, letters: 6, category: 'clothes' },
  { id: 'ambatya', text: 'אַמְבַּטְיָה', pic: '🛁', level: 6, station: 16, letters: 6, category: 'home' },
  { id: 'tarnegol', text: 'תַּרְנְגוֹל', pic: '🐓', level: 6, station: 16, letters: 6, category: 'animals' },
  { id: 'mishkafayim', text: 'מִשְׁקָפַיִם', pic: '👓', level: 6, station: 16, letters: 6, category: 'clothes' },
  { id: 'melafefon', text: 'מְלָפְפוֹן', pic: '🥒', level: 6, station: 16, letters: 6, category: 'food' },
  { id: 'agvaniya', text: 'עַגְבָנִיָּה', pic: '🍅', level: 6, station: 16, letters: 6, category: 'food' },
  { id: 'televizya', text: 'טֶלֶוִיזְיָה', pic: '📺', level: 6, station: 16, letters: 7, category: 'home' },
  { id: 'misparayim', text: 'מִסְפָּרַיִם', pic: '✂️', level: 6, station: 16, letters: 6, category: 'home' },
  { id: 'tractor', text: 'טְרַקְטוֹר', pic: '🚜', level: 6, station: 16, letters: 6, category: 'vehicles' },
  { id: 'talmid', text: 'תַּלְמִיד', pic: '', level: 6, station: 16, letters: 5, category: 'family' },
  { id: 'kfafot', text: 'כְּפָפוֹת', pic: '🧤', level: 6, station: 16, letters: 5, category: 'clothes' },
  { id: 'paamon', text: 'פַּעֲמוֹן', pic: '🔔', level: 6, station: 16, letters: 5, category: 'toys' },
  { id: 'machberet', text: 'מַחְבֶּרֶת', pic: '📓', level: 6, station: 16, letters: 5, category: 'toys' },
  { id: 'svivon', text: 'סְבִיבוֹן', pic: '', level: 6, station: 16, letters: 6, category: 'toys' },
  { id: 'maglesha', text: 'מַגְלֵשָׁה', pic: '🛝', level: 6, station: 16, letters: 5, category: 'toys' },
  { id: 'tachposet', text: 'תַּחְפֹּשֶׂת', pic: '', level: 6, station: 16, letters: 5, category: 'toys' },
  { id: 'menora', text: 'מְנוֹרָה', pic: '', level: 6, station: 16, letters: 5, category: 'home' },
  { id: 'yanshuf', text: 'יַנְשׁוּף', pic: '🦉', level: 6, station: 16, letters: 5, category: 'animals' },
  { id: 'pinguin', text: 'פִּינְגְּוִין', pic: '🐧', level: 6, station: 16, letters: 7, category: 'animals' },
  { id: 'dolfin', text: 'דּוֹלְפִין', pic: '🐬', level: 6, station: 16, letters: 6, category: 'animals' },
  { id: 'afifon', text: 'עֲפִיפוֹן', pic: '🪁', level: 6, station: 16, letters: 6, category: 'toys' },
  { id: 'mitriya', text: 'מִטְרִיָּה', pic: '☂️', level: 6, station: 16, letters: 5, category: 'home' },
  { id: 'ambulans', text: 'אַמְבּוּלַנְס', pic: '🚑', level: 6, station: 16, letters: 7, category: 'vehicles' },
  { id: 'etmol', text: 'אֶתְמוֹל', pic: '', level: 6, station: 16, letters: 5, category: 'time' },
  { id: 'chanukiya', text: 'חֲנֻכִּיָּה', pic: '🕎', level: 6, station: 16, letters: 5, category: 'toys' },
];

// השלב שמתחיל בתחנה: התחנה הראשונה של השלב.
export function stationOfStage(stage) {
  const s = Math.min(LEVELS.length, Math.max(1, Math.round(Number(stage)) || 1));
  return LEVELS[s - 1].stations[0];
}

// השלב שהתחנה שייכת אליו.
export function stageOfStation(index) {
  const i = Math.min(STATIONS.length, Math.max(1, Math.round(Number(index)) || 1));
  return STATIONS[i - 1].stage;
}

// ניקוד -> שלב. אותו כלל כמו stage_of() ב-data/validate_words.py (הבנייה בודקת שהם מסכימים).
const STAGE_OF_MARK = {
  '\u05B8': 1, '\u05B7': 1,                          // קמץ, פתח
  '\u05B4': 2,                                       // חיריק
  '\u05B9': 3, '\u05BA': 3, '\u05C7': 3,             // חולם, חולם חסר לו, קמץ קטן
  '\u05BB': 4,                                       // קובוץ (שורוק: ו עם דגש ובלי תנועה)
  '\u05B5': 5, '\u05B6': 5,                          // צירה, סגול
  '\u05B0': 6, '\u05B1': 6, '\u05B2': 6, '\u05B3': 6, // שווא, חטפים
};
const SHVA = '\u05B0', DAGESH = '\u05BC', VAV = '\u05D5', SHURUK_STAGE = 4;
const isLetter = (c) => c >= '\u05D0' && c <= '\u05EA';
const isMark = (c) => /^[\u0591-\u05BD\u05BF\u05C1\u05C2\u05C4\u05C5\u05C7]$/.test(c);

// השלב (1-6) שמילה מנוקדת צריכה. טקסט בלי ניקוד הוא שלב 1.
export function stageOfText(text) {
  const clusters = [];                               // [אות, ניקוד[], אות אחרונה במילה]
  let open = false;
  for (const c of String(text ?? '').normalize('NFD')) {
    if (isLetter(c)) { clusters.push([c, [], false]); open = true; }
    else if (isMark(c)) { if (open) clusters[clusters.length - 1][1].push(c); }
    else { if (open) clusters[clusters.length - 1][2] = true; open = false; }
  }
  if (clusters.length) clusters[clusters.length - 1][2] = true;
  let stage = 1;
  for (const [letter, marks, last] of clusters) {
    const vowels = marks.filter((m) => m in STAGE_OF_MARK);
    if (letter === VAV && marks.includes(DAGESH) && !vowels.length) {
      stage = Math.max(stage, SHURUK_STAGE);         // וּ שורוק
      continue;
    }
    for (const v of vowels) {
      if (v === SHVA && last) continue;              // שווא באות האחרונה (ךְ) לא נשמע
      stage = Math.max(stage, STAGE_OF_MARK[v]);
    }
  }
  return stage;
}
